### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by d-513** [Maximalfr/mitm_egg_ing#1]
Seems that it doesnt work anymore, partly because the endpoint was changed to save_backup_secure, and even if I change the endpoint in the script it doesn’t seem to intercept anything (running ./mitmweb -s proxy.py)

**Comment by b1bradders** [comment]
if i extract some of the code and just pass through a binary file that has the Request data from the save_backup_secure endpoint, it seems I can read & modify values manually. You'd probably have to update it entirely as this is like 7 years old now, but it can still extract values.

Whilst I'm here, you wouldn't know anywhere where I could find more documentation on the Egg Inc save data? I've gotten to that stage of trying to ask AI what the format could be but it keeps suggesting it's a Protobuf. No idea though if it's right 🤷🏻

**Comment by d-513** [comment]
Sorry, I'm not the author of the script, and I have no idea how any of this worked.
